myapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path('weather_app/', include('weather_app.urls')),
]

weather_app/urls.py
from django.urls import path
from . import views

app_name = 'weather_app'

urlpatterns = [
    path('', views.confirm, name='confirm'),
]

weather_app/models.py
from django.db import models

# Create your models here.

weather_app/views.py
from django.shortcuts import render
import requests


# Create your views here.
def confirm(request):
    
    if request.method == 'POST':

        #選択された地域のIDを取得
        choice = request.POST.get('choice') 

        #天気予報APIのURL
        base_url = 'https://weather.tsukumijima.net/api/forecast'

        #パラメータをURLエンコードする
        params = {'city': choice}

        #データをリクエスト
        response = requests.get(base_url, params=params)

        #選択した地名
        place_name = response.json()['location']['prefecture']
        
        #今日の日付
        today_date = response.json()['forecasts'][0]['date'].replace("-","/") #"-"から"/"に置換        
        
        #天気の画像
        weather_image = response.json()['forecasts'][0]['image']['url']
        
        #１日の天気の移り変わり
        change_weather = response.json()['forecasts'][0]['telop']
        
        #最高気温
        max_temp = response.json()['forecasts'][0]['temperature']['min']['celsius']
        
        #最低気温
        min_temp = response.json()['forecasts'][0]['temperature']['max']['celsius']
        
        #選択ボタンを押された際confirm.htmlに出動
        return render(request, 'weather_app/confirm.html', {'place_name': place_name, 'today_date': today_date, 'weather_image': weather_image, 'change_weather': change_weather, 'max_temp': max_temp, 'min_temp': min_temp})
        
    #GETリクエストの場合はindex.htmlを表示
    return render(request, 'weather_app/index.html')

weather_app/templates/weather_app/confirm.html
<!-- templates/confirm.html -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation</title>
</head>
<body>
    <h2>Weather Information </h2>
    <h3>{{place_name}} {{today_date}}の天気</h3>
    <img src="{{weather_image}}" alt="" width="200" height="200">
    <h4>{{change_weather}}</h4>
    <p>最高気温: {{ max_temp }}</p>
    <p>最低気温: {{ min_temp }}</p>
    <a href="{{request.META.HTTP_REFERER}}">トップページに戻る</a>
</body>
</html>

weather_app/templates/weather_app/index.html
<!-- regex_app/templates/index.html -->
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form</title>
</head>
<body>
    <h1>Weather Information</h1>
    <h2>今日の天気の知りたい場所を選択してください</h2>
    <form method="post" action="{% url 'weather_app:confirm' %}">
        {% csrf_token %}
        <select name="choice" id="choice">
            <option value="270000">大阪</option>
            <option value="280010">兵庫(神戸)</option>
            <option value="290010">奈良</option>
            <option value="300010">和歌山</option>
            <option value="260010">京都</option>
            <option value="250010">滋賀(大津)</option>
            <option value="240010">三重(津)</option>
         </select>
         <input type="submit" value="Submit">
    </form>
    
</body>
</html>